# Generated by Django 4.0.4 on 2022-06-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinTask',
        ),
    ]
