# Generated by Django 4.0.4 on 2022-06-01 01:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskr', '0002_delete_cointask'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTask',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('exchanges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=1000)),
                ('task_run', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
