# Generated by Django 4.0.4 on 2022-06-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
